/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketRouteImport } from './routes/ticket'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VTokenRouteImport } from './routes/v.$token'
import { Route as AppTicketsRouteImport } from './routes/_app/tickets'
import { Route as AppTeamRouteImport } from './routes/_app/team'
import { Route as AppProjectsRouteImport } from './routes/_app/projects'
import { Route as AppPersonalizacaoRouteImport } from './routes/_app/personalizacao'
import { Route as AppPermissoesRouteImport } from './routes/_app/permissoes'
import { Route as AppOrcamentoRouteImport } from './routes/_app/orcamento'
import { Route as AppIntegracoesRouteImport } from './routes/_app/integracoes'
import { Route as AppFinanceiroRouteImport } from './routes/_app/financeiro'
import { Route as AppFacebookRouteImport } from './routes/_app/facebook'
import { Route as AppEquipamentosRouteImport } from './routes/_app/equipamentos'
import { Route as AppDiguinhoRouteImport } from './routes/_app/diguinho'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCalendarioRouteImport } from './routes/_app/calendario'
import { Route as AppCadastrosRouteImport } from './routes/_app/cadastros'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const TicketRoute = TicketRouteImport.update({
  id: '/ticket',
  path: '/ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VTokenRoute = VTokenRouteImport.update({
  id: '/v/$token',
  path: '/v/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTicketsRoute = AppTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppPersonalizacaoRoute = AppPersonalizacaoRouteImport.update({
  id: '/personalizacao',
  path: '/personalizacao',
  getParentRoute: () => AppRoute,
} as any)
const AppPermissoesRoute = AppPermissoesRouteImport.update({
  id: '/permissoes',
  path: '/permissoes',
  getParentRoute: () => AppRoute,
} as any)
const AppOrcamentoRoute = AppOrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegracoesRoute = AppIntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppFacebookRoute = AppFacebookRouteImport.update({
  id: '/facebook',
  path: '/facebook',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipamentosRoute = AppEquipamentosRouteImport.update({
  id: '/equipamentos',
  path: '/equipamentos',
  getParentRoute: () => AppRoute,
} as any)
const AppDiguinhoRoute = AppDiguinhoRouteImport.update({
  id: '/diguinho',
  path: '/diguinho',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarioRoute = AppCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AppRoute,
} as any)
const AppCadastrosRoute = AppCadastrosRouteImport.update({
  id: '/cadastros',
  path: '/cadastros',
  getParentRoute: () => AppRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ticket': typeof TicketRoute
  '/cadastros': typeof AppCadastrosRoute
  '/calendario': typeof AppCalendarioRoute
  '/dashboard': typeof AppDashboardRoute
  '/diguinho': typeof AppDiguinhoRoute
  '/equipamentos': typeof AppEquipamentosRoute
  '/facebook': typeof AppFacebookRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/integracoes': typeof AppIntegracoesRoute
  '/orcamento': typeof AppOrcamentoRoute
  '/permissoes': typeof AppPermissoesRoute
  '/personalizacao': typeof AppPersonalizacaoRoute
  '/projects': typeof AppProjectsRoute
  '/team': typeof AppTeamRoute
  '/tickets': typeof AppTicketsRoute
  '/v/$token': typeof VTokenRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ticket': typeof TicketRoute
  '/cadastros': typeof AppCadastrosRoute
  '/calendario': typeof AppCalendarioRoute
  '/dashboard': typeof AppDashboardRoute
  '/diguinho': typeof AppDiguinhoRoute
  '/equipamentos': typeof AppEquipamentosRoute
  '/facebook': typeof AppFacebookRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/integracoes': typeof AppIntegracoesRoute
  '/orcamento': typeof AppOrcamentoRoute
  '/permissoes': typeof AppPermissoesRoute
  '/personalizacao': typeof AppPersonalizacaoRoute
  '/projects': typeof AppProjectsRoute
  '/team': typeof AppTeamRoute
  '/tickets': typeof AppTicketsRoute
  '/v/$token': typeof VTokenRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/ticket': typeof TicketRoute
  '/_app/cadastros': typeof AppCadastrosRoute
  '/_app/calendario': typeof AppCalendarioRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/diguinho': typeof AppDiguinhoRoute
  '/_app/equipamentos': typeof AppEquipamentosRoute
  '/_app/facebook': typeof AppFacebookRoute
  '/_app/financeiro': typeof AppFinanceiroRoute
  '/_app/integracoes': typeof AppIntegracoesRoute
  '/_app/orcamento': typeof AppOrcamentoRoute
  '/_app/permissoes': typeof AppPermissoesRoute
  '/_app/personalizacao': typeof AppPersonalizacaoRoute
  '/_app/projects': typeof AppProjectsRoute
  '/_app/team': typeof AppTeamRoute
  '/_app/tickets': typeof AppTicketsRoute
  '/v/$token': typeof VTokenRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ticket'
    | '/cadastros'
    | '/calendario'
    | '/dashboard'
    | '/diguinho'
    | '/equipamentos'
    | '/facebook'
    | '/financeiro'
    | '/integracoes'
    | '/orcamento'
    | '/permissoes'
    | '/personalizacao'
    | '/projects'
    | '/team'
    | '/tickets'
    | '/v/$token'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/ticket'
    | '/cadastros'
    | '/calendario'
    | '/dashboard'
    | '/diguinho'
    | '/equipamentos'
    | '/facebook'
    | '/financeiro'
    | '/integracoes'
    | '/orcamento'
    | '/permissoes'
    | '/personalizacao'
    | '/projects'
    | '/team'
    | '/tickets'
    | '/v/$token'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/ticket'
    | '/_app/cadastros'
    | '/_app/calendario'
    | '/_app/dashboard'
    | '/_app/diguinho'
    | '/_app/equipamentos'
    | '/_app/facebook'
    | '/_app/financeiro'
    | '/_app/integracoes'
    | '/_app/orcamento'
    | '/_app/permissoes'
    | '/_app/personalizacao'
    | '/_app/projects'
    | '/_app/team'
    | '/_app/tickets'
    | '/v/$token'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  TicketRoute: typeof TicketRoute
  VTokenRoute: typeof VTokenRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ticket': {
      id: '/ticket'
      path: '/ticket'
      fullPath: '/ticket'
      preLoaderRoute: typeof TicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$token': {
      id: '/v/$token'
      path: '/v/$token'
      fullPath: '/v/$token'
      preLoaderRoute: typeof VTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tickets': {
      id: '/_app/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AppTicketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/personalizacao': {
      id: '/_app/personalizacao'
      path: '/personalizacao'
      fullPath: '/personalizacao'
      preLoaderRoute: typeof AppPersonalizacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/permissoes': {
      id: '/_app/permissoes'
      path: '/permissoes'
      fullPath: '/permissoes'
      preLoaderRoute: typeof AppPermissoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orcamento': {
      id: '/_app/orcamento'
      path: '/orcamento'
      fullPath: '/orcamento'
      preLoaderRoute: typeof AppOrcamentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integracoes': {
      id: '/_app/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof AppIntegracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro': {
      id: '/_app/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/facebook': {
      id: '/_app/facebook'
      path: '/facebook'
      fullPath: '/facebook'
      preLoaderRoute: typeof AppFacebookRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/equipamentos': {
      id: '/_app/equipamentos'
      path: '/equipamentos'
      fullPath: '/equipamentos'
      preLoaderRoute: typeof AppEquipamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/diguinho': {
      id: '/_app/diguinho'
      path: '/diguinho'
      fullPath: '/diguinho'
      preLoaderRoute: typeof AppDiguinhoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendario': {
      id: '/_app/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AppCalendarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cadastros': {
      id: '/_app/cadastros'
      path: '/cadastros'
      fullPath: '/cadastros'
      preLoaderRoute: typeof AppCadastrosRouteImport
      parentRoute: typeof AppRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppCadastrosRoute: typeof AppCadastrosRoute
  AppCalendarioRoute: typeof AppCalendarioRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDiguinhoRoute: typeof AppDiguinhoRoute
  AppEquipamentosRoute: typeof AppEquipamentosRoute
  AppFacebookRoute: typeof AppFacebookRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppIntegracoesRoute: typeof AppIntegracoesRoute
  AppOrcamentoRoute: typeof AppOrcamentoRoute
  AppPermissoesRoute: typeof AppPermissoesRoute
  AppPersonalizacaoRoute: typeof AppPersonalizacaoRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppTicketsRoute: typeof AppTicketsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCadastrosRoute: AppCadastrosRoute,
  AppCalendarioRoute: AppCalendarioRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDiguinhoRoute: AppDiguinhoRoute,
  AppEquipamentosRoute: AppEquipamentosRoute,
  AppFacebookRoute: AppFacebookRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppIntegracoesRoute: AppIntegracoesRoute,
  AppOrcamentoRoute: AppOrcamentoRoute,
  AppPermissoesRoute: AppPermissoesRoute,
  AppPersonalizacaoRoute: AppPersonalizacaoRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppTeamRoute: AppTeamRoute,
  AppTicketsRoute: AppTicketsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  TicketRoute: TicketRoute,
  VTokenRoute: VTokenRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
